baseurl = "https://foodieyamwoonsen.gitlab.io/foodie_hugo_media/"
contentdir    = "content"
layoutdir     = "layouts"
publishdir    = "public"
title = "foodie media server"
canonifyurls  = true

DefaultContentLanguage = "ja"
theme = "beautifulhugo"
metaDataFormat = "yaml"
pygmentsUseClasses = true
pygmentCodeFences = true

[Params]
  subtitle = ""
  logo = "logo.png"
  favicon = "img/favicon.ico"
  dateformat = "02.01.2006" # Change the format of dates
  commit = false
  rss = false
  comments = true


[Author]
  name = "foodie.yamwoonsen.de"
