name: Deploy Media via git-ftp
on: push
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v1
      - name: git-ftp push
        uses: sebastianpopp/git-ftp-action@releases/v3
        with:
          url: ${{ secrets.FTP_HOST }}
          user: ${{ secrets.FTP_USER }}
          password: ${{ secrets.FTP_PASSWORD }}
          options: --syncroot static --remote-root ${{ secrets.FTP_SERVER_DIR }} --verbose
      - name: send notification mail
        uses: dawidd6/action-send-mail@v3
        with:
          # Required mail server address:
          server_address: smtp.mail.de
          # Required mail server port:
          server_port: 465
          # Optional (recommended): mail server username:
          username: ${{secrets.MAIL_USERNAME}}
          # Optional (recommended) mail server password:
          password: ${{secrets.MAIL_PASSWORD}}
          # Required mail subject:
          subject: Der Reiskoch Media Auto-Deployment success!
          # Required recipients' addresses:
          to: der@reisko.ch
          # Required sender full name (address can be skipped):
          from: der@reisko.ch # <der@reisko.ch>
          # Optional whether this connection use TLS (default is true if server_port is 465)
          secure: true
          # Optional plain body:
          body: Build job of ${{github.repository}} completed successfully!
          # Optional recipient of the email response:
          reply_to: der@reisko.ch
          # Optional Message ID this message is replying to:
          in_reply_to: <der@reisko.ch>
          # Optional unsigned/invalid certificates allowance:
          ignore_cert: true
          # Optional converting Markdown to HTML (set content_type to text/html too):
          convert_markdown: true
          # Optional attachments:
          priority: low

